# Generated by Django 3.1.3 on 2020-12-10 04:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.BooleanField()),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('dni', models.CharField(max_length=8)),
                ('fecha', models.DateField()),
                ('celular', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.BooleanField()),
                ('direccion_id', models.ForeignKey(db_column='direccion_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.direccion')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopago', models.CharField(max_length=9)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codper', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=9)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.cliente')),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('direccion_id', models.ForeignKey(db_column='direccion_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.direccion')),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('ruc', models.CharField(max_length=11)),
                ('estado', models.BooleanField()),
                ('direccion_id', models.ForeignKey(db_column='direccion_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.empleado')),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Detalleticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.producto')),
                ('ticket_id', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Detallesalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nrosal', models.ForeignKey(db_column='nrosal', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.salida')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalleentrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nroent', models.ForeignKey(db_column='nroent', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.entrada')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.cliente')),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appdiverxia.empleado')),
            ],
        ),
    ]
