# Generated by Django 3.1.3 on 2020-12-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdiverxia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comprobantepago',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detalleentrada',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detallesalida',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detalleticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='direccion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='empleado',
            table=None,
        ),
        migrations.AlterModelTable(
            name='entrada',
            table=None,
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='repartidor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salida',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
    ]
