# Generated by Django 3.1.4 on 2020-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiverxia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='documento_tipo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nacimiento',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
