# Generated by Django 3.1.4 on 2020-12-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiverxia', '0002_auto_20201215_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
    ]
