# Generated by Django 3.1.3 on 2020-12-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdiverxia', '0002_auto_20201209_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='auth_user',
        ),
    ]
